Added rq to run "label-studio-ml init my_backend"
I was getting the follow runtime error because rq is used but not imported:

from rq import Queue, get_current_job
ModuleNotFoundError: No module named 'rq'